"""
Configuration File
Customize application settings here
"""

# Model Configuration
MODEL_PATH = "best_oto.pt"
MODEL_CONFIDENCE_DEFAULT = 0.5

# UI Configuration
WINDOW_TITLE = "Smart Traffic Car Counting System"
WINDOW_SUBTITLE = "Image Enhancement + YOLO11 Detection"
WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 900

# Theme Configuration
USE_DARK_THEME = False  # Set to True for dark theme

# Image Enhancement Defaults
DEFAULT_CLAHE_CLIP = 2.0
DEFAULT_CLAHE_GRID = (8, 8)
DEFAULT_GAMMA = 1.0
DEFAULT_BRIGHTNESS = 0
DEFAULT_CONTRAST = 1.0
DEFAULT_DENOISE = 0

# Detection Configuration
DETECTION_CLASSES = ['car', 'vehicle']  # Classes to count
BOX_COLOR = (0, 255, 0)  # Green in BGR
TEXT_COLOR = (255, 255, 255)  # White in BGR
BOX_THICKNESS = 2

# Export Configuration
EXPORT_IMAGE_FORMAT = "jpg"
EXPORT_IMAGE_QUALITY = 95
EXPORT_REPORT_FORMAT = "txt"

# Performance Configuration
MAX_IMAGE_SIZE = (1920, 1080)  # Max resolution for processing
ENABLE_GPU = True  # Use GPU if available

# UI Colors (Fluent Design)
PRIMARY_COLOR = "#0078D4"  # Blue
SECONDARY_COLOR = "#666666"  # Gray
SUCCESS_COLOR = "#107C10"  # Green
WARNING_COLOR = "#FF8C00"  # Orange
ERROR_COLOR = "#E81123"  # Red

# File Filters
SUPPORTED_IMAGE_FORMATS = "Image Files (*.png *.jpg *.jpeg *.bmp *.tiff)"

# Processing
SHOW_PROCESSING_INFO = True
AUTO_ENHANCE_ON_UPLOAD = False  # Automatically enhance after upload
AUTO_DETECT_ON_ENHANCE = False  # Automatically detect after enhancement

# Statistics
SHOW_DETAILED_STATS = True
DECIMAL_PLACES = 2

# Pipeline Steps
PIPELINE_STEPS = [
    "Upload Image",
    "Enhance Image", 
    "YOLO11 Detection",
    "Count Cars"
]

# Slider Ranges (for customization)
SLIDER_RANGES = {
    'clahe_clip': (1.0, 5.0, 2.0),  # (min, max, default)
    'gamma': (0.5, 3.0, 1.0),
    'brightness': (-100, 100, 0),
    'contrast': (0.5, 2.5, 1.0),
    'denoise': (0, 30, 0),
    'confidence': (0.1, 0.9, 0.5)
}

# Grid Size Options
GRID_SIZE_OPTIONS = ["4x4", "8x8", "16x16"]
GRID_SIZE_MAP = {
    "4x4": (4, 4),
    "8x8": (8, 8),
    "16x16": (16, 16)
}

# Info Messages
INFO_MESSAGES = {
    'model_loaded': "YOLO model loaded successfully",
    'model_error': "Failed to load model. Please check best_oto.pt",
    'image_loaded': "Image loaded successfully!",
    'image_error': "Failed to load image",
    'enhancement_applied': "Enhancement applied successfully!",
    'detection_complete': "Detection complete!",
    'export_success': "Results exported successfully!",
    'no_image': "Please upload an image first",
    'no_enhancement': "Please apply enhancement first"
}

# Report Template
REPORT_TEMPLATE = """
{'=' * 50}
Smart Traffic Car Counting System - Report
{'=' * 50}

Image: {image_path}
Date: {date}

Results:
  Cars Detected: {car_count}
  Processing Time: {processing_time}
  Image Resolution: {resolution}
  Average Confidence: {avg_confidence}

Enhancement Parameters:
  CLAHE Clip Limit: {clahe_clip}
  CLAHE Grid Size: {clahe_grid}
  Gamma: {gamma}
  Brightness: {brightness}
  Contrast: {contrast}
  Denoising: {denoise}
  Confidence Threshold: {confidence}

{'=' * 50}
Generated by Smart Traffic Car Counting System
{'=' * 50}
"""
